### ISSUE TITLE
Question: Folder colours

### ISSUE THREAD

**Issue by Miyo9190** [cryham/themes#1]
Hello, I am using your `doublecmd.xml` template (just updated the colours XML part) and I don't know what is the reasoning for having folders with different colours. Is this something on Double Commander side or your file types? As per this image:
![doublecmd_7sRIlA303q](https://user-images.githubusercontent.com/23096738/127188316-498ea38c-b090-4b07-9792-8bf026f2dd25.png)

Do these folder have any difference in order to have different colours (permissions, size...)?

**Comment by cryham** [comment]
I do also color folders in my themes. Looks like it got "program" and did green.
It is possible to change that but not that easy disable all. Either way I use my program https://github.com/cryham/ccc to export xml, not the xml since years.
